### ISSUE TITLE
Block cannot be edited

### ISSUE THREAD

**Issue by Visual-Notes** [Remo/concrete5-zoom-image#4]
When Zoom Image is added to a page, configured and saved, it cannot be edited anymore. When clicking "Edit Block" in the context menu, the loading animation rotates but nothing happens.

**Comment by Remo** [comment]
can you please try the latest version from github? should work now

**Comment by Visual-Notes** [comment]
Works fine now, thank you!

**Comment by Remo** [comment]
cool, thanks for confirming!
